# tools/patch_generator.py — AI patch generation + GitHub PR push

import re
import uuid
from retrieval.hybrid_search import hybrid_search
from llm.ollama_client import ask_ollama
from llm.prompt_templates import patch_prompt
from github_client import create_branch_and_commit, create_pull_request


async def generate_patch(repo_full: str, issue_description: str) -> dict:
    """
    1. Search the repo for relevant code chunks
    2. Ask the LLM to generate a unified diff
    3. Parse the diff into file-level changes
    4. Return patch + structured file list for preview
    """
    # Get relevant context
    chunks = await hybrid_search(repo_full, issue_description, top_k=5)

    # Generate patch via LLM
    prompt = patch_prompt(repo_full, issue_description, chunks)
    raw_patch = await ask_ollama(prompt)

    # Parse the diff to extract file-level metadata for the UI
    files = _parse_diff_files(raw_patch)

    return {
        "patch": raw_patch,
        "files": files,
    }


async def push_patch_as_pr(repo_full: str, patch: str, title: str) -> str:
    """
    Apply the patch to a new branch and open a GitHub PR.
    Returns the PR URL.
    """
    branch_name = f"repomind/fix-{uuid.uuid4().hex[:8]}"

    # Parse patch into file changes
    file_changes = _patch_to_file_changes(patch)

    if not file_changes:
        raise ValueError("Could not parse any file changes from the patch")

    # Create branch + commit
    await create_branch_and_commit(
        repo_full_name=repo_full,
        branch_name=branch_name,
        file_changes=file_changes,
        commit_message=f"fix: {title}\n\nGenerated by RepoMind AI",
    )

    # Open PR
    pr_url = await create_pull_request(
        repo_full_name=repo_full,
        branch_name=branch_name,
        title=title,
        body=(
            f"## AI-Generated Fix\n\n"
            f"**Description:** {title}\n\n"
            f"This PR was generated by [RepoMind](https://github.com/your/repomind).\n\n"
            f"Please review carefully before merging.\n\n"
            f"<details>\n<summary>Raw patch</summary>\n\n```diff\n{patch}\n```\n</details>"
        ),
    )

    return pr_url


def _parse_diff_files(patch: str) -> list[dict]:
    """
    Parse a unified diff string into a list of:
    {filename, additions, deletions, patch (the hunk)}
    for display in the UI.
    """
    files = []
    current_file = None
    current_lines = []
    additions = 0
    deletions = 0

    for line in patch.splitlines():
        if line.startswith("+++ b/") or line.startswith("+++ "):
            # Save previous file
            if current_file:
                files.append({
                    "filename":  current_file,
                    "additions": additions,
                    "deletions": deletions,
                    "patch":     "\n".join(current_lines),
                })
            current_file = line.replace("+++ b/", "").replace("+++ ", "").strip()
            current_lines = []
            additions = 0
            deletions = 0
        elif line.startswith("--- "):
            continue  # skip "from" header
        elif current_file:
            current_lines.append(line)
            if line.startswith("+") and not line.startswith("+++"):
                additions += 1
            elif line.startswith("-") and not line.startswith("---"):
                deletions += 1

    # Save last file
    if current_file:
        files.append({
            "filename":  current_file,
            "additions": additions,
            "deletions": deletions,
            "patch":     "\n".join(current_lines),
        })

    return files


def _patch_to_file_changes(patch: str) -> list[dict]:
    """
    Convert a unified diff into {path, content} pairs suitable for
    create_branch_and_commit. This is a simplified approach — it extracts
    only the added lines as the new file content.

    For a production system you'd want a proper patch-apply library.
    """
    file_changes = []
    files = _parse_diff_files(patch)

    for f in files:
        # Extract only the '+' lines (new content) from the hunk
        new_lines = []
        for line in f["patch"].splitlines():
            if line.startswith("@@"):
                continue
            elif line.startswith("+"):
                new_lines.append(line[1:])  # strip leading '+'
            elif not line.startswith("-"):
                new_lines.append(line[1:] if line.startswith(" ") else line)

        if new_lines:
            file_changes.append({
                "path":    f["filename"],
                "content": "\n".join(new_lines),
            })

    return file_changes
